version: '3.9'

services:

  web:
    container_name: traffic_flow
    build:
      context: .
    command: python server.py
    volumes:
      - ./traffic_flow:/usr/src/traffic_flow
    ports:
      - 8000:8000
